### PR TITLE
Fix bug where clicking an untamed mob with node inspector causes a crash

### LINKED ISSUE #269: Fix bug where clicking an untamed mob with node inspector causes a crash
See https://github.com/BlockySurvival/replacer/pull/1

### PR DESCRIPTION
**Pull request by afkplayer5000**
Closes BlockySurvival/issue-tracker#269

### CODE REVIEW

File: inspect.lua [hunk 1]
```diff
@@ -78,7 +78,11 @@ replacer.inspect = function(_, user, pointed_thing, mode, show_receipe)
 			end
 
 		end
-		text = text..' at '..minetest.pos_to_string(ref:getpos())
+		if ref:getpos() then
+			text = text..' at '..minetest.pos_to_string(ref:getpos())
```
Comment (luk3yx) [inline inspect.lua]: The `getpos()` function is deprecated (it was there before this PR but would be a good improvement anyway).
```suggestion
		if ref:get_pos() then
			text = text..' at '..minetest.pos_to_string(ref:get_pos())
```

**Comment by luk3yx** [comment]
Thanks for the PR.
